exclude: ^src/autocast/external/.*$

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.14
  hooks:
    # Run the linter.
    - id: ruff-check
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]
- repo: https://github.com/astral-sh/ty-pre-commit
  rev: v0.0.55
  hooks:
    - id: ty
- repo: https://github.com/kynan/nbstripout
  rev: 0.9.0
  hooks:
  - id: nbstripout
